### ISSUE TITLE
Does pix2pix is good for face transformation?

### ISSUE THREAD

**Issue by wb-08** [junyanz/pytorch-CycleGAN-and-pix2pix#1128]
I'm trying to make different face masks like faceapp,snapchat. Does pix2pix is  good for this?

**Comment by junyanz** [comment]
Using pix2pix is possible. But you need to collect many pairs of input face and transformed face, which might be challenging in pratice.

**Comment by wb08work** [comment]
thanks you for the answer) it is possible to use pix2pix with a resolution of 512x512? I already tried, but I got bad results, even though I changed the --ngf and --ndf parameters. With a resolution of 256x256 works well!

**Comment by junyanz** [comment]
You can use [pix2pixHD](https://github.com/NVIDIA/pix2pixHD) or [SPADE](https://github.com/NVlabs/SPADE) for high-resolution image synthesis. If you want to use pix2pix, you can try to train a model on 256x256 crops rather than original images. See this [Tip](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/tips.md#trainingtesting-with-high-res-images).

**Comment by wb08work** [comment]
thank you very much)
