### ISSUE TITLE
cyclegan: Shift and deformation in medical image translation - how to create a good training dataset

### ISSUE THREAD

**Issue by dyollb** [junyanz/pytorch-CycleGAN-and-pix2pix#1310]
I am training using cyclegan with medical (MRI T1) images of the head and neck from two hospitals to learn the difference in appearance. I would like the generated image to have similar contours (anatomy) but different style. 

It seems however, that after some epochs I get more predictions that shift the generated image or deform it. The head foreground region is not perfectly centered because I did some random cropping to generate the slices as 256x256 resolution.

- I am running with following command line: `python src\train.py --dataroot ./cyclegan/T1a_to_T1b--name T1a_to_T1b --model cycle_gan --input_nc 1 --output_nc 1 --gan_mode lsgan --preprocess crop`
- I have around 5000 grayscale images for trainA and trainB each (slices of around 15 different heads).

I will try the other `gan_mode` options, but wonder if this has to do with some bias in my training data. Should I ensure that the center of mass (image intensity) has a similar distribution for `trainA` and `trainB`? Can you give any recommendations how to create a good training dataset? Should I add e.g. rotation augmented training data?

To get a rough idea of the distribution of the training data:
![train_data_cyclegan](https://user-images.githubusercontent.com/12702862/130793254-37cf1b90-21d9-4b36-a180-622bbd7f93e2.PNG)

**Comment by junyanz** [comment]
You could either (1) align the images for two datasets, (2) train a model on cropped patches rather than the full images. 
There are probably other techniques for medical imaging, which I am not familiar with. Here are a few papers. [[1]](https://aapm.onlinelibrary.wiley.com/doi/pdf/10.1002/mp.13617?casa_token=dDzeVHO-LhoAAAAA%3A7UsgISYQr8Hn4UniDwbZFH-w8SYjv8ZKyQXS2ADnXRLn6bqDfdi0jNNhgxDuqCIJvXwHmFmuPY9U), [[2]](https://www.sciencedirect.com/science/article/pii/S0167814019331172?casa_token=d5tiTpO-eBsAAAAA:Z_plLWFfrIn36Gp01zGsIf1OHrPAOX2H3JKBngOCrhVQb6XYEHeLx2yphePs9qkpzsCtZdY),

**Comment by dyollb** [comment]
> You could either (1) align the images for two datasets, (2) train a model on cropped patches rather than the full images. There are probably other techniques for medical imaging, which I am not familiar with. Here are a few papers. [[1]](https://aapm.onlinelibrary.wiley.com/doi/pdf/10.1002/mp.13617?casa_token=dDzeVHO-LhoAAAAA%3A7UsgISYQr8Hn4UniDwbZFH-w8SYjv8ZKyQXS2ADnXRLn6bqDfdi0jNNhgxDuqCIJvXwHmFmuPY9U), [[2]](https://www.sciencedirect.com/science/article/pii/S0167814019331172?casa_token=d5tiTpO-eBsAAAAA:Z_plLWFfrIn36Gp01zGsIf1OHrPAOX2H3JKBngOCrhVQb6XYEHeLx2yphePs9qkpzsCtZdY),

thanks, i will try with the patch-based approach.
