### ISSUE TITLE
CUDA out of memory. Tried to allocate 20.00 MiB (GPU 0; 4.00 GiB total capacity; 2.34 GiB already allocated; 5.14 MiB free; 2.48 GiB reserved in total by PyTorch)

### ISSUE THREAD

**Issue by wenjingyi** [junyanz/pytorch-CycleGAN-and-pix2pix#1322]
I  have used the data which from the CycleGAN dataset, how to resolve this question? Dose resize its pixel size? now is 600*600. THX

**Comment by wenjingyi** [comment]
the memory of CUDA is more than 2GiB

**Comment by AlexWilkinsonnn** [comment]
You can try putting `torch.cuda.empty_cache()` after each iteration. This isn't really recommended though since it will mean slow training and you might still get the same OOM error. For cycleGAN I would think a 4Gb card is too small, if you don't have access to a bigger card you will need to use smaller images.

**Comment by mavihs09** [comment]
@wenjingyi either
 (i) use much smaller images, 
(ii) try different batch size combinations (if you have batch size >2)
(iii) trim the datasize (in case you are using custom dataset)

Either of these three might help you out
