### ISSUE TITLE
训练参数问题

### ISSUE THREAD

**Issue by Jy-stdio** [junyanz/pytorch-CycleGAN-and-pix2pix#1379]
你好，你们的工作非常棒，看完之后收获很大。
想问您一下，我用自己未对齐的数据训练pix2pix的话，训练命令参数的设置上有没有说明文档呢？
是否在训练时设置`--dataset_mode unaligned`代表对未对齐数据进行训练？
期待您的答复
谢谢

**Comment by junyanz** [comment]
Yes, `-dataset_mode unaligned` means that the training is using unpaired data. For unpaired data, you should use cyclegan rather than pix2pix. For more details regarding hyperparameters, please refer to [train options](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/options/train_options.py) and test [options](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/options/test_options.py). Also refer to [Q&A](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/qa.md) and [training & test tips](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/docs/tips.md).
