### ISSUE TITLE
The ONNX network's output '625' dimensions should be non-negative

### ISSUE THREAD

**Issue by youjinChung** [junyanz/pytorch-CycleGAN-and-pix2pix#1469]
Hello,

I am trying to convert a cyclegan model to onnx.
I referred [this answer](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/issues/1113#issuecomment-728681741) for onnx importing, and it worked without errors.
But the thing is, when I try to import the onnx file to the onnx runtime(Snap Lens Studio), I got this error below
`Resource import for /Users/youjin/Downloads/latest_net_G (1).onnx failed: The ONNX network's output '625' dimensions should be non-negative`
![image](https://user-images.githubusercontent.com/18349962/184219391-d87e3148-b661-4875-87b3-40798310a275.png)
When I see the structure of the model, the '625' is the output node, and the dimension is unknown, which is considered as '-1'.

I wonder where I can find the output node and if anyone has an idea to set it to the right dimension.

**Comment by youjinChung** [comment]
It was the issue that Snap Lens Studio could only import compressed GANs.
I could solve it by training with the Snap-released GAN repo.

**Comment by Jbla0712** [comment]
> It was the issue that Snap Lens Studio could only import compressed GANs. I could solve it by training with the Snap-released GAN repo.

Thanks i have the same problem! Can you link me the deposit you have use? 
Thank you miss

**Comment by Jbla0712** [comment]
cause have CAT https://github.com/snap-research/CAT

or https://github.com/Snapchat/snapml-templates/blob/main/Image-to-Image%20Translation/Image_to_Image_translation_with_GAN_Compression.ipynb

**Comment by youjin-c** [comment]
Hi @Jbla0712 , I think you can try either of them. Either will work for this.

**Comment by Jbla0712** [comment]
> Hi @Jbla0712 , I think you can try either of them. Either will work for this.

Thank you for answering me, that's nice because it's difficult for a self-taught person.  
I asked the snapteam to update the repository because it will be useful given the progress of Lens Studio 
(I invite you to try it if you haven't done so for a long time). 

WELLl, I now know that using the apentit and teacher method from CAT will allow me to have a functional ONNX in Lens Studio.

If you find a nice and up-to-date repository, please share it with me. 
I'm having trouble doing Teacher Training and Student Training. there is little information on this method unlike cyclegan


Happy New Year 2025, thank you again for answering me, it’s motivating 🙋‍♂️Good luck on your side
