### ISSUE TITLE
can size of generated images as large as original images

### ISSUE THREAD

**Issue by botaichang** [junyanz/pytorch-CycleGAN-and-pix2pix#224]
when i make inference, the size of my test image is 500x1000 for example, i also want to get a generated image which size is also 500x1000? how can i get this, i see the resize_or_crop param have many options but have no option for keep original size?

**Comment by junyanz** [comment]
See this post #206

**Comment by mrluker** [comment]
@botaichang  @junyanz 

I have been able to generate test images at 2800x1880 using a 1070 (8gb VRAM) using --model cycle_gan --dataset_mode unaligned instead of --model test --dataset_mode single

using --model test appears to take more VRAM and thus can only run at a lower resolution

see: https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/issues/236

**Comment by junyanz** [comment]
Fixed.
