### ISSUE TITLE
How does the identity weight affect the outcome?

### ISSUE THREAD

**Issue by taki0112** [junyanz/pytorch-CycleGAN-and-pix2pix#249]
How does the `identity weight` affect the outcome?

For the current code, you gave a weight of `0.5` 
Did you try this when you gave it `1`? What's the difference?

**Comment by taesung89** [comment]
It does not result in a big difference. 

With higher identity loss, the image translation becomes more conservative, so it makes less changes. I tried using values like 0.1, 0.5, 1 and 10, and the result is not so different. I believe this is because the generator figures out essentially two different translation functions by detecting whether the input image is from the source dataset or the target dataset.
