### ISSUE TITLE
Train network without scaling or cropping

### ISSUE THREAD

**Issue by alecalma** [junyanz/pytorch-CycleGAN-and-pix2pix#250]
Is there an option to train without resizing the dataset? It seems like I have to select one of the 4 alternatives [resize_and_crop|crop|scale_width|scale_width_and_crop]. Thank you.

**Comment by taesung89** [comment]
You can specify `--resize_or_crop none`. However, you will get an error if an input image has size that is not a multiple of 4, because the default resnet generator changes the image shape after downsamplings and upsamplings. To avoid that, you can add your custom if clause in `get_transform` function of `base_dataset.py` to resize the image to be multiple of 4.
