### ISSUE TITLE
Confused with "self.loss_G_A = self.criterionGAN(self.netD_A(self.fake_B), True)

### ISSUE THREAD

**Issue by yifanw90** [junyanz/pytorch-CycleGAN-and-pix2pix#260]
Dear,  thanks for the awesome work! 
In the file "cycle_gan_model.py",  function 'backward_G',   I'm confused with "self.loss_G_A = self.criterionGAN(self.netD_A(self.fake_B), True)"  (in line 135) .  why not self.criterionGAN(self.netD_B(self.fake_B), True).  
Also in line 139: self.loss_G_B = self.criterionGAN(self.netD_B(self.fake_A), True)
Have I misunderstood anything else?  Could you please explain it?
Thank you!

**Comment by HugoGranstrom** [comment]
I think it has to do with that Generator A takes an image from A as input and outputs an image that is supposed to look like the images from B. Discriminator B is trained to evaluate how muchh an image looks like an image from B.
Ex horse2zebra: 
A are images of horses and B are images of zebras. D_A trains on the horse images (A) to be able to determine if a picture is a horse, D_B train on zebra pictures. G_A takes horse images as input and output an image that is supposed to look like a zebra image. So G_A is trying to convert an image from A to B (horse to zebra). To see how much the generated "zebra image" looks like a zebra we let D_B evaluate how much it looks like a zebra. We can't let D_A determine that because it just tells you how likely it is for an image to be a horse which we aren't interested in because we generated a zebra image. 

I hope this cleared up some things at least. If I was unclear about something or this didn't make sense tell me and I will try another way of saying it :)

**Comment by yifanw90** [comment]
@HugoGranstrom   Dear, Sincerely thank you for your detailed explanation.  :)
So  I think the original code in Line 135 and 139 in the"cycle_gan_model.py" should be modified as  "self.loss_G_A = self.criterionGAN(self.netD_B(self.fake_B), True)" and  "self.loss_G_B = self.criterionGAN(self.netD_A(self.fake_A), True)", respectively.  Am I right?

**Comment by HugoGranstrom** [comment]
@yifanw90 I got them mixed up above as well, sorry. I have edited my answer now.
D_A tells you how likely it is for an image to be a zebra and D_B tells you how likely it is that an image is a horse. Not the other way around as I first wrote above. So the code in "cycle_gan_model.py" is correct. 

G_A(A) -> fake B image -> D_A(fake B image)  -> does it look like B? Yes/No.

**Comment by yifanw90** [comment]
@HugoGranstrom ,  Dear, Thank you so much for your help.  I get it now!
