### ISSUE TITLE
Running on a remote server

### ISSUE THREAD

**Issue by mhusseinsh** [junyanz/pytorch-CycleGAN-and-pix2pix#329]
Hello,

I am training the network on a remote server, which does not have any browser.
Is there a way to view the results on visdom from my local machine ?

**Comment by calebescobedo** [comment]
Hey mhusseinsh, I had this exact same problem! 

I'm gonna write out what I did and hopefully it will help you.  

1) On your own computer create run `touch ~/.ssh/config ` to create a ssh configuration file where you can specify some setting for when you ssh. 

2) In that ssh config file you can create a new host to specific settings for this remote server 
Example:
normally you would run something like
`ssh username@address` 
In the config file add this as a new entry
```
Host nameForSSHing
    HostName address
    User username 
    LocalForward 127.0.0.1:8097 127.0.0.1:8097
```
3) now you can use `ssh nameForSSHing`
this website helped me: https://www.digitalocean.com/community/tutorials/how-to-configure-custom-connection-options-for-your-ssh-client

4) When I ran the actual code on the test server I also I first started the visdom server using 
`visdom` and it game me link so that I could view the results as they came in. 

5) Finally when running train.py on my remote server I added the flag `--display_server "http://address"` where address is the name of the ssh address mentioned earlier. 

Let me know if any of these parts are unneeded to run the code!

**Comment by taesung89** [comment]
Awesome! I am glad to know that too.

**Comment by calebescobedo** [comment]
I'm not sure that you can specify the .ssh/config file on windows in the same way. 

Alternatively you could use the windows powershell.

You first need to allow ssh to be used in powershell,[ this tutorial](https://www.howtogeek.com/336775/how-to-enable-and-use-windows-10s-built-in-ssh-commands/) can help you with that. 

Then when you ssh you need to specify that you want to local port forward. 
For example run `ssh -L 8097:127.0.0.1:8097 username@address`

After you do that refer to step 4 above. 

Let me know if that works out!
