### ISSUE TITLE
About visualizing the results by .html files.

### ISSUE THREAD

**Issue by dustyYMelody7** [junyanz/pytorch-CycleGAN-and-pix2pix#348]
I run your code, the training and test process is successfully. But when i want to visualize the results(pictures) on web following the suggestion by this sentence. It didn't show any pictures in web.
Could you tell me how should I do to visualize the pictures in web or any problems about my path?
![image](https://user-images.githubusercontent.com/31617882/44138489-b5017688-a0a6-11e8-9aa9-f3130f36ab26.png)

![image](https://user-images.githubusercontent.com/31617882/44138537-d80b1c24-a0a6-11e8-826c-1ef9094e6f3a.png)

**Comment by junyanz** [comment]
Interesting. Are there images in the `images` directory? Does the HTML visualization work for the provided datasets (e.g., facades)?

**Comment by qihuaiyu** [comment]
I have solved this problem. Thanks a lot. The reason is that I open the HTML file in local IE. I tried to connect the server using jupyter notebook in local browser, and it worked. Another question is that I want to know how should I change the code to process this situation: training two inputs images to generate one output image?

**Comment by junyanz** [comment]
You need to write your own data loader. See #320 for more details.

**Comment by qihuaiyu** [comment]
Thanks a lot! I will try it.
