### ISSUE TITLE
winter2summer dataset are not available

### ISSUE THREAD

**Issue by parmidaatg** [junyanz/pytorch-CycleGAN-and-pix2pix#375]
Hello, 

I checked out your master branch and the winter2summer-yosemit is not part of the available datasets. The summer2winter is available though. Should I just simply change the A to B mapping for the folders? 

Thanks

**Comment by parmidaatg** [comment]
Also, I tested your winter2summer pretrained model for some random images, it seems that it works nicely only if there is snow in winter. when I dont have snow, then it produces bluish color instead of green to change the scene. I glanced your dataset and it seems to be very diverse so I was expecting a result similar to what you have posted on the sample images. I am going to finetune your model on a more diverse data that I have but is there anything that I am missing before i start doing it ?

**Comment by taesung89** [comment]
Yes. 

We have datasets in only one direction, because the opposite direction can be simply used by using `--which_direction BtoA` in training and testing. 

For the pretrained model, there's still a subtle difference between the Torch and PyTorch implementation of CycleGAN, although it's hard to say which one is better. If you'd like results that are exactly same as the ones appearing in the paper, please use our Torch implementation.

**Comment by parmidaatg** [comment]
Thanks a lot for your response
