### ISSUE TITLE
mode collapse?

### ISSUE THREAD

**Issue by YilinLiu97** [junyanz/pytorch-CycleGAN-and-pix2pix#421]
Hi @junyanz, I found that either the test goes from A to B or B to A, I got the exact same contents with just different styles. The style was indeed transferred correctly, but the contents do not seem to belong to either A or B but a different image C. I'm wondering what might be the causes for that?? BTW these are brain images.

**Comment by junyanz** [comment]
probably mode collapse. You may want to increase the training set size or add more data augmentation.

**Comment by m-pektas** [comment]
Hi, I have a question about pix2pix training. Generally, People trains pix2pix model for domain translation. But I have 10k image pair that have same domain and style but have minor differences in some local areas. I trained my model but got mode collapse error. Could the mode collapse be caused by the pairs having the same domain?
