### ISSUE TITLE
using pretrained models but results not happening

### ISSUE THREAD

**Issue by javismiles** [junyanz/pytorch-CycleGAN-and-pix2pix#533]
Good day, 
I download pretrained models from
http://efrosgans.eecs.berkeley.edu/pix2pix/models-pytorch/monet2photo.pth

that one and others.

Then I set them in the right directory with the name:
latest_net_G.pth
for just one side or:
latest_net_G_A.pth
latest_net_G_B.pth
for both sides

then I put some tests photos in a folder and run this command

!python CYC/test.py --dataroot testA --name t --model test --no_dropout --checkpoints_dir tests --results_dir testresults

for just one side, or this one for both:

!python CYC/test.py --dataroot testmonet --name t --model cycle_gan --no_dropout --checkpoints_dir tests --results_dir testresults

and no errors, all executes perfect, but the results show nothing, nothing really changes in the test pictures, why not? what's going wrong? am I missing something here? thank you

**Comment by taesungp** [comment]
Hello, 

I suspect it's because you used actual photographs as test images?

The pretrained model `monet2photo.pth` changes Monet's paintings into photo-style. It should not change anything if you use photos as input. (Please refer to the _identity_ loss_ of the paper and `--identity` option in this code repo. `monet2photo` was trained with this option). I think you used actual photographs when you put the test photos. You may want to input Monet's paintings if you'd like to use this pretrained model.

**Comment by javismiles** [comment]
you are right, because I did the same with Van Gogh and the japanese painter and it all works perfect with them, and it only fails with Monet and it is what you say, I was using normal photos yes

In the Monet one, there  is no option we can put to make it go the other way? thank you again for your great creation

**Comment by taesungp** [comment]
Hi Javis, 

you can use this file: 

[http://efrosgans.eecs.berkeley.edu/cyclegan/pretrained_models/style_monet.pth](http://efrosgans.eecs.berkeley.edu/cyclegan/pretrained_models/style_monet.pth)

It's probably a bug on our side that monet2photo.pth file exists under pix2pix. Painting <-> photo codes should exist in cyclegan directory of the web space.

**Comment by javismiles** [comment]
Very helpful, thanks very much @taesungp  ;)
