### ISSUE TITLE
Retain image size

### ISSUE THREAD

**Issue by ryanaleksander** [junyanz/pytorch-CycleGAN-and-pix2pix#562]
I've tried a pretrained model and it turns out that the network would resize the input and output to a certain pre-defined size. Is it possible to use the network without resizing during test time? For example, if I input an image at 1920 x 1080, the output image would also be at 1920 x 1080.

**Comment by yuanzhoulvpi2017** [comment]
This is not the case, because this network, the image requirements you enter can only be like this, if you want to change the output image, you use the function to adjust

**Comment by taesungp** [comment]
It is possible, but you should retrain the model at that resolution. You can use the option `--preprocess none` to disable image resizing. By the way, 1920x1080 is very high resolution for CycleGAN so it won't fit on most GPUs. We recommend that you train with something like `--preprocess crop --crop_size 512`, so that the model is trained with only cropped portions of the entire image. At test time, you can probably do `--preprocess none` because the memory requirement is significantly lower at test time.
