### ISSUE TITLE
512x512 image with test.py?

### ISSUE THREAD

**Issue by CrackerHax** [junyanz/pytorch-CycleGAN-and-pix2pix#643]
All I am getting is a 256x512 image. Setting --window_size, --load_size, and/or --crop_size doesn't seem to help.

**Comment by CrackerHax** [comment]
Nope. I retrained in 512... still getting images that aren't the right size.

**Comment by junyanz** [comment]
Could you share with us more details? Are you using pix2pix or CycleGAN? What is your test script command?  One possible scenario: you are testing pix2pix but your input data only contain 512x512 input image. If you use `--model pix2pix` during test time, the test  script will divide this 512x512 image into two images. Each image is 256x512, because the input data should include both input and output images.  One workaround solution is to use `--model test`. See [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix#apply-a-pre-trained-model-cyclegan) for more details.

**Comment by CrackerHax** [comment]
When I try to use model test I get 
`AttributeError:` 'Sequential' object has no attribute 'model'

**Comment by junyanz** [comment]
Maybe adding `--netG unet --norm batch`. See this [post](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/issues/358) for more details.

**Comment by CrackerHax** [comment]
Yes I already tried that as per the document and got 
`NotImplementedError: Generator model name [unet] is not recognized`

**Comment by CrackerHax** [comment]
Ok for anybody else who had this problem here is what I used and it worked:
`!python test.py --dataroot ./datasets/AB --name face2segment_pix2pix --netG unet_256 --norm batch --dataset_mode single --model test --gpu_ids 0  --preprocess none --epoch latest --no_dropout --load_size 512 --crop_size 512`
