### ISSUE TITLE
Datasets cannot be downloaded 

### ISSUE THREAD

**Issue by coditive** [junyanz/pytorch-CycleGAN-and-pix2pix#787]
hi! I cannot download datasets for cyclegan for testing model. Please Help!
![error](https://user-images.githubusercontent.com/41199211/66584643-2685a480-eba3-11e9-9ad9-edf4f370f49f.png)

**Comment by silyman1** [comment]
I have the same problem

**Comment by BITWN** [comment]
I found the server has been shutdown temporarily from Oct. 9 due to fire danger.
![image](https://user-images.githubusercontent.com/23192817/66633992-b4629d80-ec3e-11e9-88a9-296b1d0c5957.png)
![image](https://user-images.githubusercontent.com/23192817/66633964-9c8b1980-ec3e-11e9-827d-b127baf65c29.png)

**Comment by BITWN** [comment]
another Issue may be help: https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/issues/785

**Comment by junyanz** [comment]
Please refer to #785. You can download some of the datasets from Kaggle.

**Comment by coditive** [comment]
Thank you for your help, i downloaded these datasets from kaggle.
