### ISSUE TITLE
What are nThreads, resize_or_crop, and pool_size doing?

### ISSUE THREAD

**Issue by isalirezag** [junyanz/pytorch-CycleGAN-and-pix2pix#80]
So I read the help part for the parameters that are used, but I am a little confused regarding nThreads, resize_or_crop, and pool_size…

nThreads: the default value is 2 and it says “# threads for loading data”, what exactly does it means?

resize_or_crop: scaling and cropping of images at load time, the default='resize_and_crop'; so what should I do if I want to just crop the image at load time and don’t care about its original size and do not resize it? should I use crop instead of resize_and_crop?

pool_size: it says pool_size is “the size of image buffer that stores previously generated images” and it is set to default=50, can anyone explain to me what it means?

Thanks

**Comment by phillipi** [comment]
nThreads: the data loader is [multithreaded](https://en.wikipedia.org/wiki/Multithreading_(computer_architecture)) so that it can use multiple CPU cores to load images.

resize_or_crop: yeah, I think 'crop' will do what you want.

pool_size: the discriminator is trained against the current batch of generated images as well as images generated on previous iterations. Essentially, we remember the last pool_size generated images then randomly sample from this pool to create a batch_size batch of images to do one iteration of backprop on. This helps to stabilize training, kind of like experience replay.
