### ISSUE TITLE
Some questions about choosing GANs

### ISSUE THREAD

**Issue by HeoJinLareine** [junyanz/pytorch-CycleGAN-and-pix2pix#847]
1.
I'm trying to train a model for this use.
trainA: before some works or procedure.
trainB: Same place, but after some works or procedure.

By this model, If I put a pre-work(procedure) place's image, want to get after GAN image.

In this case, pix2pix or CycleGAN ( or even other GAN) is more suitable in your guess?
(I'm quite new in computer science ...)

2.
And for training, I've added  ( --epoch 400 ) at the end of training code. 
But it really did train for 200..
is there any way to solve this?

3.
for pix2pix model, do I have to merge input-output image? 
(for example, input & output is 256x256, does it works as 512 x 256)

**Comment by junyanz** [comment]
1. It depends on if you have paired data. In your case, if you have two photos taken from the same camera angle and position before and after. If you have paired data, use pix2pix. Otherwise, use CycleGAN
2. The correct flags are `--iter` and `--iter_decay`. See the [flag](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/options/train_options.py#L30).
3. You need to merge them for pix2pix.

**Comment by Jiang-maomao** [comment]
If I have paired data, pix2pix is better than Cyclegan?

**Comment by junyanz** [comment]
Yes.
