### ISSUE TITLE
how can I use 'continue_train' option?

### ISSUE THREAD

**Issue by khryang** [junyanz/pytorch-CycleGAN-and-pix2pix#87]
Hi~ I'm again,
I want to train with the latest model of previous training.
I used the commend flag "--continue_train" and others were same with previous training
but the training epoch started at 1 epoch
is there any more options to need?

**Comment by junyanz** [comment]
I just added the `--epoch_count` flag. By default, the program will initialize the epoch count as 1. Set `--epoch_count` to specify a different starting epoch count.

**Comment by khryang** [comment]
@junyanz  thanks for your answer.
where can I find the comment about 'epoch_count' in your code?
I can't find it in the code of 'train_option' and 'base_option'

**Comment by junyanz** [comment]
It was recently added [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/options/train_options.py#L12).

**Comment by khryang** [comment]
@junyanz  good! thank you!!

**Comment by khryang** [comment]
@junyanz Hi~
I have one more question about 'continue_train'
the commend for train is
'python train.py --dataroot, --name, --model, etc...'

I'm wondering which pre-trained net in the directory of checkpoints will be called up, if I use --continue_train flag? is it that name what I wrote with name flag?? then continuing training results are saved at the same name??
for example, I want to make new directory 'new_result' of running for 'contine_train'  from pre-trained net of named 'my_data' . I think there is not that option, isn't it??

very basically, I'm looking for part of calling for pre_trained network in your code.
please let me know that part.

thank you very much^^

**Comment by vin-ni** [comment]
Hi,
I tried to continue training like that:
`-dataroot ./datasets/opaGan --name opa_cyclegan --model cycle_gan --epoch_count 200 --continue_train` but it just did the 200th epoch and then stopped. Is this the max training size or can I go up to epoch 400?

**Comment by junyanz** [comment]
It should stop at 200, as niter=200, niter_decay=200, and you start from epoch_count=200. If you want to train it longer, you can increase niter and/or niter_decay . See more details about these flags [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/options/train_options.py#L20).

**Comment by skgshivam** [comment]
> It was recently added [here](https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/options/train_options.py#L12).



> I just added the `--epoch_count` flag. By default, the program will initialize the epoch count as 1. Set `--epoch_count` to specify a different starting epoch count.

Should I give --epoch_count value the last epoch at which training the model stopped along with --continue_train

**Comment by junyanz** [comment]
Yes.

**Comment by Himanshu-Garg** [comment]
`!python train.py --dataroot ./datasets/fonts_AB --name fonts_pix2pix --model pix2pix --direction AtoB --checkpoints_dir /content/drive/MyDrive/pix2pix_checkpoints
`
Here, if i run the above code again and again, it always start epoch from 1... Does it mean that it resets the weights each time I run the cell, OR continue training the model from the last checkpoint (i.e. epoch 1 means that 1 new epoch has been done from the last checkpoint)???

@junyanz

**Comment by Fai-yong** [comment]
`-dataroot ./datasets/opaGan --name opa_cyclegan --model cycle_gan --epoch_count 200 --continue_train`

can I use this command to train a model base on a pre-trained model? or not? what does  '--model cycle_gan' mean? using the pre-trained model in the path './checkpoint/cycle_gan' ?

I've got the official dataset from [https://people.eecs.berkeley.edu/~taesung_park/CycleGAN/datasets/](https://people.eecs.berkeley.edu/~taesung_park/CycleGAN/datasets/)
however, it needs a huge graphics memory to train (using the official dataset ), I have only a laptop with one RTX4060, how can I do some option to only train some of part of the whole network instead of training all of it?

If can, are there any suggestions about fine-tuning a pre-trained model? like adding some codes in certain places of the project, since I'm not an expert in using cycleGAN.
